import BroadcastReceiver from "android.content.BroadcastReceiver"

import {ICallbackFunc} from "./interface.uts"

export class HeadSetReceiver extends BroadcastReceiver {
  private callback: ICallbackFunc
  constructor(callback: ICallbackFunc) {
	  super();
    this.callback = callback
  }
  // 重写onReceive事件
  override onReceive(context, intent) {
    console.log("收到广播: " + intent.getAction());
  } 
}